### ISSUE TITLE
Data mapping

### ISSUE THREAD

**Issue by hylickipiotr** [scottkellum/CJSS#11]
Hello, I saw your example and I wanted to simplify the code by using data maping, but I think is something wrong in your script. I based my code on the JSX language. I think, you will need to considere this to integrate it to your project.

**Before:**
```css
nav {
  --data:(
    links: ['one', 'two', 'three'],
  );
  --html:(
    <div class="item">${data.links[0]}</div>
    <div class="item">${data.links[1]}</div>
    <div class="item">${data.links[2]}</div>
  );
}
```

**After:**
```css
nav {
  --data:(
    links: ['one', 'two', 'three'],
  );
  --html:(
  ${data.links.map(link => <div>${link}</div>}
  );
}
```
